import { assert, assertClose, fins, prop, WEB } from './_util.js';
import { unzip } from '../web/zip.js';
import { isStep, releaseStepWorker } from '../web/step.js';

// SEC-02: Cloudflare static-asset security and cache headers
Deno.test('SEC-02: web/_headers declares global security headers and cache policies', () => {
  const content = Deno.readTextFileSync(new URL('../web/_headers', import.meta.url));

  // Security headers under /*
  assert(content.includes('/*'), 'contains /* section');
  assert(content.includes('X-Content-Type-Options: nosniff'), 'X-Content-Type-Options');
  assert(content.includes('X-Frame-Options: DENY'), 'X-Frame-Options');
  assert(content.includes('Referrer-Policy: strict-origin-when-cross-origin'), 'Referrer-Policy');
  assert(content.includes('Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()'), 'Permissions-Policy');
  assert(content.includes("Content-Security-Policy: default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'"), 'Content-Security-Policy');

  // Application cache rules
  assert(content.includes('/index.html\n  Cache-Control: no-cache, no-store, must-revalidate'), 'index.html cache policy');
  assert(content.includes('/*.js\n  Cache-Control: public, max-age=0, must-revalidate'), 'js cache policy');
  assert(content.includes('/*.css\n  Cache-Control: public, max-age=0, must-revalidate'), 'css cache policy');

  // Vendor immutability rules
  assert(content.includes('/vendor/occt-import-js-0.0.23/*\n  Cache-Control: public, max-age=31536000, immutable'), 'occt cache policy');
  assert(content.includes('/vendor/three/*\n  Cache-Control: public, max-age=31536000, immutable'), 'three cache policy');
});

// CAD-CONC-03: Web Worker top-level error handlers
Deno.test('CAD-CONC-03: web/finworker.js and web/stepworker.js have top-level error handlers', () => {
  const finworker = Deno.readTextFileSync(new URL('../web/finworker.js', import.meta.url));
  assert(finworker.includes('self.onerror = (e) => {'), 'finworker onerror');
  assert(finworker.includes('self.onunhandledrejection = (e) => {'), 'finworker onunhandledrejection');

  const stepworker = Deno.readTextFileSync(new URL('../web/stepworker.js', import.meta.url));
  assert(stepworker.includes('self.onerror = (e) => {'), 'stepworker onerror');
  assert(stepworker.includes('self.onunhandledrejection = (e) => {'), 'stepworker onunhandledrejection');
});

// CAD-LOGIC-01 & GEOM-LOGIC-006: Tunables idempotence, tineBite propagation, sway braces options
Deno.test('CAD-LOGIC-01: applyTunables propagates tineBite to PROP and is idempotent', () => {
  try {
    // 1. applyTunables sets tineBite in both FIN and PROP
    fins.applyTunables({ tineBite: 0.18, finGap: 0.35 });
    assert(fins.FIN.tineBite === 0.18, 'FIN.tineBite applied');
    assert(prop.PROP.tineBite === 0.18, 'PROP.tineBite propagated');
    assert(fins.FIN.gap === 0.35, 'FIN.gap applied');

    // 2. Applying new tunables without tineBite resets tineBite back to baseline default (0.3)
    fins.applyTunables({ finGap: 0.22 });
    assert(fins.FIN.gap === 0.22, 'FIN.gap updated');
    assert(fins.FIN.tineBite === 0.3, 'FIN.tineBite reset to default');
    assert(prop.PROP.tineBite === 0.5, 'PROP.tineBite reset to default');
  } finally {
    // Reset to defaults
    fins.applyTunables({ finGap: 0.2, tineBite: 0.3, propGap: 0.2 });
  }
});

// CAD-LOGIC-03: Unchecked DataView offsets in unzip
Deno.test('CAD-LOGIC-03: unzip rejects out-of-bounds central directory and local headers', async () => {
  // Truncated ZIP with corrupt EOCD pointing past buffer length
  const fakeEocd = new Uint8Array(22);
  const view = new DataView(fakeEocd.buffer);
  view.setUint32(0, 0x06054b50, true); // EOCD signature
  view.setUint16(8, 1, true);          // 1 entry
  view.setUint16(10, 1, true);
  view.setUint32(12, 46, true);        // size
  view.setUint32(16, 1000, true);      // offset out of bounds

  let threw = false;
  try {
    await unzip(fakeEocd);
  } catch (err) {
    threw = true;
    assert(err.message.includes('out of bounds') || err.message.includes('corrupt'), 'expected bounds error');
  }
  assert(threw, 'unzip should throw on out-of-bounds central directory');
});

// CAD-LOGIC-05: isStep leading comments and whitespace
Deno.test('CAD-LOGIC-05: isStep recognizes STEP Part 21 with leading comments and whitespace', () => {
  const enc = new TextEncoder();
  const withComment = enc.encode('/* ISO-10303-21 STEP File generated by CAD */\nISO-10303-21;\nHEADER;\n');
  assert(isStep(withComment.buffer), 'STEP with leading C-style comment should be detected');

  const withBomAndComment = enc.encode('\uFEFF/* Leading comment */\n  ISO-10303-21;\nHEADER;\n');
  assert(isStep(withBomAndComment.buffer), 'STEP with BOM and leading comment should be detected');

  const plainCommentOnly = enc.encode('/* Not a step file */ solid model\n');
  assert(!isStep(plainCommentOnly.buffer), 'Non-STEP file with leading comment should be rejected');
});

// CAD-LOGIC-06: releaseStepWorker
Deno.test('CAD-LOGIC-06: releaseStepWorker terminates worker without throwing', () => {
  assert(typeof releaseStepWorker === 'function', 'releaseStepWorker is an exported function');
  releaseStepWorker(); // Safe to call even when worker is null
});
